# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def basicFrameworks
  
  pod 'Moya/RxSwift'
  pod 'RxSwift'
  pod 'RxCocoa'
  
end

target 'Network' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Network
  basicFrameworks
end

target 'TADA_HomeWork' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TADA_HomeWork
  basicFrameworks
  pod 'SnapKit', '~> 5.0.0'
  pod 'Kingfisher', '~> 6.0'
  pod 'Then'
  
  target 'TADA_HomeWorkTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TADA_HomeWorkUITests' do
    # Pods for testing
  end

end
